# Generated by Django 5.1.1 on 2024-12-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_educa_plus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("videos", models.JSONField()),
                ("quantidade_videos", models.IntegerField()),
            ],
        ),
    ]
